# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OI0nV_yddwTUvsjHXjHZdRr3Zp5RmaG8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('Churn_Modelling.csv')
df.head(5)

df.info()

df.describe()

df.columns

plt.rcParams['figure.figsize'] = (9,9)
sm = sns.heatmap(df[['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']].corr(), annot = True, cmap = 'Blues')
sm.set_title('Heatmap Distribution')

df.head(5)

subset = df[df.Geography.isin(['France', 'Spain', 'Germany'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x = 'Geography', y = 'Age', data = subset)
ax.set_title('Countries v/s Age')

subset = df[df.Geography.isin(['France', 'Spain', 'Germany'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Geography', y='Balance', data = subset)
ax.set_title('Countries v/s Balance')

subset = df[df.Geography.isin(['France', 'Spain', 'Germany'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Geography', y='NumOfProducts', data = subset)
ax.set_title('Countries v/s Products')

subset = df[df.Geography.isin(['France', 'Spain', 'Germany'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Geography', y='HasCrCard', data = subset)
ax.set_title('Countries v/s Credit Card')

subset = df[df.Geography.isin(['France', 'Spain', 'Germany'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Geography', y='EstimatedSalary', data = subset)
ax.set_title('Countries v/s Salary')

subset = df[df.Gender.isin(['Male', 'Female'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Gender', y='Balance', data=subset)
ax.set_title('Gender v/s Balance')

subset = df[df.Gender.isin(['Male', 'Female'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Gender', y='EstimatedSalary', data=subset)
ax.set_title('Gender v/s Salary')

subset = df[df.Gender.isin(['Male', 'Female'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Gender', y='Tenure', data=subset)
ax.set_title('Gender v/s Tenure')

subset = df[df.Geography.isin(['France', 'Spain', 'Germany'])]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Geography', y='Tenure', data = subset)
ax.set_title('Countries v/s Tenure')

df.columns

X = df[['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary' ]]
Y = df['Exited']

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X,Y)

import statsmodels.api as sm
X = sm.add_constant(X)
lm_1 = sm.OLS(Y,X).fit()
print(lm_1.summary())

X = df[['CreditScore', 'Age', 'Balance', 'IsActiveMember']]
Y = df['Exited']

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X,Y)

import statsmodels.api as sm
X = sm.add_constant(X)
lm_1 = sm.OLS(Y,X).fit()
print(lm_1.summary())

some_countries = ('France', 'Spain', 'Germany')
subset = df.loc[df['Geography'].isin(some_countries) & df['Age']]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x='Geography', y='Exited', data = subset)
ax.set_title('Geography & Age v/s Exited')

some_countries = ('France', 'Spain', 'Germany')
subset = df.loc[df['Geography'].isin(some_countries) & df['Balance']]
fig, ax = plt.subplots()
fig.set_size_inches(15,8)
ax = sns.violinplot(x = 'Geography', y = 'Exited', data = subset)
ax.set_title('Geography & Balance v/s Exited')